
java_library(
    name = "filter",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:aspectjweaver",
        "//lib:commons-logging",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/core/type",
        "//spring-core/src/main/java/org/springframework/core/type/classreading",
    ],
)
