
java_library(
    name = "event",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-aop/src/main/java/org/aopalliance/intercept",
        "//spring-aop/src/main/java/org/springframework/aop/framework/autoproxy",
        "//spring-aop/src/main/java/org/springframework/aop/scope",
        "//spring-aop/src/main/java/org/springframework/aop/support",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-context/src/main/java/org/springframework/context",
        "//spring-context/src/main/java/org/springframework/context/expression",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-expression/src/main/java/org/springframework/expression",
    ]
)
