
java_library(
    name = "expression",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-core/src/main/java/org/springframework/asm",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/convert",
        "//spring-core/src/main/java/org/springframework/core/env",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-expression/src/main/java/org/springframework/expression",
        "//spring-expression/src/main/java/org/springframework/expression/spel",
        "//spring-expression/src/main/java/org/springframework/expression/spel/standard",
        "//spring-expression/src/main/java/org/springframework/expression/spel/support",
    ]
)
