
java_library(
    name = "request",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//lib:faces-api",
        "//lib:log4j",
        "//lib:portlet-api",
        "//lib:servlet-api",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-context/src/main/java/org/springframework/context/i18n",
        "//spring-context/src/main/java/org/springframework/ui",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-web/src/main/java/org/springframework/http",
        "//spring-web/src/main/java/org/springframework/web/util",
    ],
)
