
java_library(
    name = "xml",
    srcs = glob(["*.java"]),
    resources = ["//spring-beans/src/main/resources:schemas"],
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-beans/src/main/java/org/springframework/beans/factory/parsing",
        "//spring-beans/src/main/java/org/springframework/beans/factory/support",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/env",
        "//spring-core/src/main/java/org/springframework/core/io",
        "//spring-core/src/main/java/org/springframework/core/io/support",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-core/src/main/java/org/springframework/util/xml",
    ]
)
