
java_library(
    name = "metadata",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-context/src/main/java/org/springframework/jmx",
        "//spring-context/src/main/java/org/springframework/jmx/support",
    ],
)
