
java_library(
    name = "core",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-core/src/main/java/org/springframework/asm",
        "//spring-core/src/main/java/org/springframework/lang",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)

#spring-core/src/main/java/org/springframework/core/type
#spring-core/src/main/java/org/springframework/core/type/classreading
#spring-core/src/main/java/org/springframework/core/type/filter
#spring-core/src/main/java/org/springframework/core/convert
#spring-core/src/main/java/org/springframework/core/convert/converter
#spring-core/src/main/java/org/springframework/core/convert/support
#spring-core/src/main/java/org/springframework/core/io
#spring-core/src/main/java/org/springframework/core/io/support
#spring-core/src/main/java/org/springframework/core/env
#spring-core/src/main/java/org/springframework/core/task
#spring-core/src/main/java/org/springframework/core/task/support
#spring-core/src/main/java/org/springframework/core/serializer
#spring-core/src/main/java/org/springframework/core/serializer/support
#spring-core/src/main/java/org/springframework/core/annotation
#spring-core/src/main/java/org/springframework/core/style
