
java_library(
    name = "naming",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-aop/src/main/java/org/springframework/aop/support",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-context/src/main/java/org/springframework/jmx/export/metadata",
        "//spring-context/src/main/java/org/springframework/jmx/support",
        "//spring-core/src/main/java/org/springframework/core/io",
        "//spring-core/src/main/java/org/springframework/core/io/support",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
