
java_library(
    name = "autoproxy",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-aop/src/main/java/org/aopalliance/aop",
        "//spring-aop/src/main/java/org/springframework/aop",
        "//spring-aop/src/main/java/org/springframework/aop/framework",
        "//spring-aop/src/main/java/org/springframework/aop/framework/adapter",
        "//spring-aop/src/main/java/org/springframework/aop/support",
        "//spring-aop/src/main/java/org/springframework/aop/target",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
