
java_library(
    name = "support",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-aop/src/main/java/org/aopalliance/aop",
        "//spring-aop/src/main/java/org/aopalliance/intercept",
        "//spring-aop/src/main/java/org/springframework/aop",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
