
sudo: true

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - unzip

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.2.3/bazel-0.2.3-installer-linux-x86_64.sh
  - chmod +x bazel-0.2.3-installer-linux-x86_64.sh
  - ./bazel-0.2.3-installer-linux-x86_64.sh --user

script:
  - bazel test //... --test_output=all

cache:
  directories:
    - $HOME/.cache/bazel

before_cache:
  - rm -rvf $HOME/.cache/bazel/_bazel_$USER/install

