
java_library(
    name = "annotation",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-beans/src/main/java/org/springframework/beans/factory/support",
        "//spring-beans/src/main/java/org/springframework/beans/factory/wiring",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/core/type",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
