
java_library(
    name = "io",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/env",
        "//spring-core/src/main/java/org/springframework/lang",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
