
java_library(
    name = "annotation",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
