
java_library(
    name = "xml",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
