
java_library(
    name = "annotation",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/annotation",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-context/src/main/java/org/springframework/jmx/export",
        "//spring-context/src/main/java/org/springframework/jmx/export/assembler",
        "//spring-context/src/main/java/org/springframework/jmx/export/metadata",
        "//spring-context/src/main/java/org/springframework/jmx/export/naming",
        "//spring-context/src/main/java/org/springframework/jmx/support",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
