
java_library(
    name = "scope",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-aop/src/main/java/org/springframework/aop",
        "//spring-aop/src/main/java/org/springframework/aop/framework",
        "//spring-aop/src/main/java/org/springframework/aop/framework/autoproxy",
        "//spring-aop/src/main/java/org/springframework/aop/support",
        "//spring-aop/src/main/java/org/springframework/aop/target",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-beans/src/main/java/org/springframework/beans/factory/support",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
