
java_test(
    name = "ComponentBeanDefinitionParserTests",
    srcs = glob(["*.java"]),
    deps = [
        "//lib:hamcrest-all",
        "//lib:junit",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-beans/src/main/java/org/springframework/beans/factory/support",
        "//spring-beans/src/main/java/org/springframework/beans/factory/xml",
        "//spring-core/src/main/java/org/springframework/core/io",
        "//spring-core/src/main/java/org/springframework/util/xml",
    ],
    size = "small",
    resources = ["//src/test/resources"],
    visibility = ["//visibility:public"],
)
