
java_library(
    name = "support",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-aop/src/main/java/org/springframework/aop",
        "//spring-aop/src/main/java/org/springframework/aop/framework",
        "//spring-aop/src/main/java/org/springframework/aop/target",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-context/src/main/java/org/springframework/jmx",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
