
java_library(
    name = "context",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//lib:servlet-api",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/access",
        "//spring-context/src/main/java/org/springframework/context",
        "//spring-context/src/main/java/org/springframework/context/access",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/core/env",
        "//spring-core/src/main/java/org/springframework/core/io",
        "//spring-core/src/main/java/org/springframework/core/io/support",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-web/src/main/java/org/springframework/web",
    ],
)
