
java_library(
    name = "env",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//lib:jopt-simple",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/convert",
        "//spring-core/src/main/java/org/springframework/core/convert/support",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
