
java_library(
    name = "support",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-context/src/main/java/org/springframework/jndi",
        "//spring-core/src/main/java/org/springframework/core",
    ],
)
