
java_library(
    name = "support",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/core/env",
        "//spring-core/src/main/java/org/springframework/core/io",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
