
java_library(
    name = "web",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//lib:el-api",
        "//lib:jsp-api",
        "//lib:servlet-api",
        "//lib:taglibs-standard-jstlel",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-core/src/main/java/org/springframework/core/io",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-web/src/main/java/org/springframework/http",
        "//spring-web/src/main/java/org/springframework/web/multipart",
        "//spring-web/src/main/java/org/springframework/web/util",
    ],
)
