
java_library(
    name = "autoproxy",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:aspectjweaver",
        "//spring-aop/src/main/java/org/aopalliance/aop",
        "//spring-aop/src/main/java/org/springframework/aop",
        "//spring-aop/src/main/java/org/springframework/aop/aspectj",
        "//spring-aop/src/main/java/org/springframework/aop/framework/autoproxy",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)

