
java_library(
    name = "aspectj",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:aspectjweaver",
        "//lib:commons-logging",
        "//spring-aop/src/main/java/org/aopalliance/aop",
        "//spring-aop/src/main/java/org/aopalliance/intercept",
        "//spring-aop/src/main/java/org/springframework/aop",
        "//spring-aop/src/main/java/org/springframework/aop/framework",
        "//spring-aop/src/main/java/org/springframework/aop/framework/autoproxy",
        "//spring-aop/src/main/java/org/springframework/aop/interceptor",
        "//spring-aop/src/main/java/org/springframework/aop/support",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
