
java_library(
    name = "support",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-context/src/main/java/org/springframework/context",
        "//spring-context/src/main/java/org/springframework/context/support",
        "//spring-context/src/main/java/org/springframework/ui/context",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
