java_library(
    name = "ast",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-core/src/main/java/org/springframework/asm",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/convert",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-expression/src/main/java/org/springframework/expression",
        "//spring-expression/src/main/java/org/springframework/expression/common",
        "//spring-expression/src/main/java/org/springframework/expression/spel",
        "//spring-expression/src/main/java/org/springframework/expression/spel/support",
    ]
)
