
java_library(
    name = "web",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:servlet-api",
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-web/src/main/java/org/springframework/http",
    ],
)
