
java_library(
    name = "type",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-core/src/main/java/org/springframework/core/annotation",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
