
java_library(
    name = "aop",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-aop/src/main/java/org/aopalliance/aop",
        "//spring-aop/src/main/java/org/aopalliance/intercept",
        "//spring-core/src/main/java/org/springframework/core",
    ]
)
