
java_library(
    name = "converter",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-core/src/main/java/org/springframework/core/convert",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-core/src/main/java/org/springframework/util/comparator",
    ]
)
