
java_library(
    name = "export",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-aop/src/main/java/org/springframework/aop/framework",
        "//spring-aop/src/main/java/org/springframework/aop/scope",
        "//spring-aop/src/main/java/org/springframework/aop/support",
        "//spring-aop/src/main/java/org/springframework/aop/target",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-context/src/main/java/org/springframework/jmx",
        "//spring-context/src/main/java/org/springframework/jmx/export/assembler",
        "//spring-context/src/main/java/org/springframework/jmx/export/naming",
        "//spring-context/src/main/java/org/springframework/jmx/export/notification",
        "//spring-context/src/main/java/org/springframework/jmx/support",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
