
java_library(
    name = "jndi",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-aop/src/main/java/org/aopalliance/intercept",
        "//spring-aop/src/main/java/org/springframework/aop",
        "//spring-aop/src/main/java/org/springframework/aop/framework",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-beans/src/main/java/org/springframework/beans/propertyeditors",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/env",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
