
java_library(
    name = "concurrent",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-core/src/main/java/org/springframework/lang",
    ],
)
