java_library(
    deps = [
        "//lib:log4j",
        "//lib:commons-codec",
        "//lib:commons-logging",
        "//spring-core/src/main/java/org/springframework/lang",
    ],
    name = "util",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
