
java_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:portlet-api",
        "//lib:servlet-api",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-web/src/main/java/org/springframework/web/util",
    ]
)
