
java_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//lib:jsp-api",
        "//lib:servlet-api",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-web/src/main/java/org/springframework/http",
        "//spring-web/src/main/java/org/springframework/http/server",
    ],
)
