
java_library(
    name = "classloading",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/lang",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-instrument/src/main/java/org/springframework/instrument",
    ]
)
