
java_library(
    name = "groovy",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//external:groovy",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-context/src/main/java/org/springframework/scripting",
        "//spring-context/src/main/java/org/springframework/scripting/support",
    ]
)
