
filegroup(
    name = "resources",
    srcs = glob([
        "**/*.xml",
        "com/foo/component.xsd",
        "log4j.properties",
        "META-INF/spring.*",
    ]),
    visibility = ["//visibility:public"],
)
