
java_library(
    name = "propertyeditors",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-core/src/main/java/org/springframework/core/io",
        "//spring-core/src/main/java/org/springframework/core/io/support",
        "//spring-core/src/main/java/org/springframework/lang",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
