
java_library(
    name = "notification",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-context/src/main/java/org/springframework/jmx",
        "//spring-core/src/main/java/org/springframework/util",
    ],
)
