
java_library(
    name = "work",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:connector-api",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-context/src/main/java/org/springframework/jndi",
        "//spring-context/src/main/java/org/springframework/scheduling",
        "//spring-core/src/main/java/org/springframework/core/task",
        "//spring-core/src/main/java/org/springframework/util",
        "//spring-core/src/main/java/org/springframework/util/concurrent",
        "//spring-tx/src/main/java/org/springframework/jca/context",
    ],
)
