
java_library(
    name = "support",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib:commons-logging",
        "//lib:spring-cglib-repack",
        "//spring-aop/src/main/java/org/springframework/aop",
        "//spring-aop/src/main/java/org/springframework/aop/framework",
        "//spring-aop/src/main/java/org/springframework/aop/support",
        "//spring-aop/src/main/java/org/springframework/aop/target/dynamic",
        "//spring-beans/src/main/java/org/springframework/beans",
        "//spring-beans/src/main/java/org/springframework/beans/factory",
        "//spring-beans/src/main/java/org/springframework/beans/factory/config",
        "//spring-beans/src/main/java/org/springframework/beans/factory/support",
        "//spring-context/src/main/java/org/springframework/context",
        "//spring-context/src/main/java/org/springframework/scripting",
        "//spring-core/src/main/java/org/springframework/asm",
        "//spring-core/src/main/java/org/springframework/core",
        "//spring-core/src/main/java/org/springframework/core/io",
        "//spring-core/src/main/java/org/springframework/core/io/support",
        "//spring-core/src/main/java/org/springframework/util",
    ]
)
